apiVersion: v1
kind: Service
metadata:
  name: web-app-service
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app.kubernetes.io/name: nginx-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.0.171.239
  type: LoadBalancer